services:
  n1:
    container_name: n1
    image: nats:2.10.12
    entrypoint: /nats-server
    command: "--config /config/jetstream.conf --server_name S1"
    networks:
      - nats
    ports:
      - 4222:4222
    volumes:
      - ./config:/config
      - n1-data:/data/nats-server/jetstream

  n2:
    container_name: n2
    image: nats:2.10.12
    entrypoint: /nats-server
    command: "--config /config/jetstream.conf --server_name S2"
    networks:
      - nats
    ports:
      - 4223:4222
    volumes:
      - ./config:/config
      - n2-data:/data/nats-server/jetstream

  n3:
    container_name: n3
    image: nats:2.10.12
    entrypoint: /nats-server
    command: "--config /config/jetstream.conf --server_name S3"
    networks:
      - nats
    ports:
      - 4224:4222
    volumes:
      - ./config:/config
      - n3-data:/data/nats-server/jetstream

networks:
  nats: {}

volumes:
  n1-data:
    driver: local
  n2-data:
    driver: local
  n3-data:
    driver: local
